name: 'Partior - Yaml Importer to GitHub flat variable'
description: 'Read and create an YAML importer file into GitHub Actions flat variable'
inputs:
  yaml-file:  
    description: 'Path to YAML file'
    required: true
    default: 'default-config.yaml'
  yaml-file-for-default:  
    description: 'Path to YAML file which contain default value'
    required: false
    default: ''
  query-path:  
    description: 'YAML query path'
    required: false
    default: ''
  query-path-for-default:  
    description: 'YAML query path for default value'
    required: false
    default: ''
  set-sub-default-keys:  
    description: 'Comma delimited sub default keys'
    required: false
    default: ''
  set-sub-default-keys-for-default:  
    description: 'Comma delimited sub default keys on default value file'
    required: false
    default: ''
  output-file:  
    description: 'Custom path of the output file'
    required: false
    default: ''
  upload:  
    description: 'Flag to indicate if require to upload the importer file'
    required: false
    default: false
outputs:
  importer-filename:
    description: "Filename of the importer script"
    value: ${{ steps.importer.outputs.filename }}
runs:
  using: "composite"
  steps:
    - name: update YQ
      run: wget https://github.com/mikefarah/yq/releases/download/v4.20.1/yq_linux_amd64.tar.gz -O - | tar xz && sudo mv yq_linux_amd64 /usr/bin/yq
      shell: bash
    - name: clean cache files
      run: echo "::set-output name=filename::$(echo $(${{ github.action_path }}/scripts/clean-files.sh ${{ inputs.output-file }} ))"
      shell: bash
    - name: create importer for default value
      if: inputs.yaml-file-for-default != ''
      run: ${{ github.action_path }}/scripts/yaml-converter.sh "${{ inputs.yaml-file-for-default }}" "${{ inputs.query-path-for-default-for-default }}" "${{ inputs.output-file }}" "${{ inputs.set-sub-default-keys }}"
      shell: bash
    - name: create importer
      run: ${{ github.action_path }}/scripts/yaml-converter.sh "${{ inputs.yaml-file }}" "${{ inputs.query-path }}" "${{ inputs.output-file }}" "${{ inputs.set-sub-default-keys }}"
      shell: bash
    - id: importer
      run: echo "::set-output name=filename::$(echo $(${{ github.action_path }}/scripts/get-importer-filename.sh ${{ inputs.output-file }} ))"
      shell: bash
    - uses: actions/upload-artifact@v2
      if: inputs.upload == 'true'
      with:
        name: ${{ steps.importer.outputs.filename }}
        path: ${{ steps.importer.outputs.filename }}
        retention-days: 1
    - run: echo Done creating importer file...
      shell: bash
