name: 'Partior - Yaml Importer to GitHub flat variable'
description: 'Read and create an YAML importer file into GitHub Actions flat variable'
inputs:
  yaml-file:  
    description: 'Path to YAML file'
    required: true
    default: 'default-config.yaml'
  yaml-file-for-default:  
    description: 'Path to YAML file which contain default value'
    required: false
    default: ''
  query-path:  
    description: 'YAML query path'
    required: false
    default: ''
  query-path-for-default:  
    description: 'YAML query path for default value'
    required: false
    default: ''
  set-sub-default-keys:  
    description: 'Comma delimited sub default keys from yaml-file file. ie: ci.branches.default,ci.another.default'
    required: false
    default: ''
  set-sub-default-keys-for-default:  
    description: 'Comma delimited sub default keys from yaml-file-for-default file. ie: ci.branches.default,ci.another.default'
    required: false
    default: ''
  output-file:  
    description: 'Custom path of the output file'
    required: false
    default: ''
  upload:  
    description: 'Flag to indicate if require to upload the importer file'
    required: false
    default: false
  override-artifact-base-name:  
    description: 'Override artifact base name'
    required: false
    default: ''
outputs:
  importer-filename:
    description: "Filename of the importer script"
    value: ${{ steps.importer.outputs.filename }}
runs:
  using: "composite"
  steps:
    - name: clean cache files
      run: echo "filename=$(echo $(${{ github.action_path }}/scripts/clean-files.sh ${{ inputs.output-file }} ))" >> $GITHUB_OUTPUT
      shell: bash
    - name: Override artifact-base-name
      if: inputs.override-artifact-base-name != ''
      run: |
        echo "[INFO] Start overriding artifact base name with [${{ inputs.override-artifact-base-name }}]..."
        yamlFiles="${{ inputs.yaml-file-for-default }} ${{ inputs.yaml-file }}"
        for eachYamlFile in $yamlFiles
        do
          echo "[INFO] Updating... [$eachYamlFile]"
          currentArtifactBaseName=$(yq e '.action-pack.ci.artifact-base-name' "$eachYamlFile")
          if [[ -z "$currentArtifactBaseName" ]] || [[ "$currentArtifactBaseName" == "null" ]]; then
            echo "[INFO] Base name not found. Skipping.."
          else
            yq e -i ".action-pack.ci.artifact-base-name = \"${{ inputs.override-artifact-base-name }}\"" "$eachYamlFile"
            echo "[INFO] Base name updated successfully..."
          fi
        done
      shell: bash
    - name: create importer for default value
      if: inputs.yaml-file-for-default != ''
      run: ${{ github.action_path }}/scripts/yaml-converter.sh "${{ inputs.yaml-file-for-default }}" "${{ inputs.query-path-for-default }}" "${{ inputs.output-file }}" "${{ inputs.set-sub-default-keys-for-default }}"
      shell: bash
    - name: create importer
      run: ${{ github.action_path }}/scripts/yaml-converter.sh "${{ inputs.yaml-file }}" "${{ inputs.query-path }}" "${{ inputs.output-file }}" "${{ inputs.set-sub-default-keys }}" "${{ inputs.yaml-file-for-default }}"
      shell: bash
    - id: importer
      run: echo "filename=$(echo $(${{ github.action_path }}/scripts/get-importer-filename.sh ${{ inputs.output-file }} ))" >> $GITHUB_OUTPUT
      shell: bash
    - uses: actions/upload-artifact@v4
      if: inputs.upload == 'true'
      with:
        name: ${{ steps.importer.outputs.filename }}
        path: ${{ steps.importer.outputs.filename }}
        retention-days: 14
        overwrite: true
    - run: echo Done creating importer file...
      shell: bash
